baseURL = 'https://zeroicey.me/'
theme = 'hugo-PaperMod'
defaultContentLanguage = 'zh'
title = '雪宁韵'

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params]
  env = 'production'
  comments = true
  defaultTheme = 'auto'
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  displayFullLangName = true
  preconnect = ['https://s3.blog.zeroicey.me']

  [params.assets]
    favicon = 'favicon.ico'

  [params.giscus]
    repo = 'zeroicey/blog'
    repoID = 'R_kgDOSjjc-g'
    category = 'General'
    categoryID = 'DIC_kwDOSjjc-s4DC64_'
    mapping = 'pathname'
    theme = 'preferred_color_scheme'
    loading = 'lazy'
    reactionsEnabled = '1'

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/zeroicey'

  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:zeroicey.hp@gmail.com'

[languages.zh]
  label = '中文'
  weight = 1
  title = '雪宁韵'

  [languages.zh.params]
    author = '雪宁韵'
    description = '雪宁韵的个人博客'
    keywords = ['blog', 'personal', 'hugo']

    [languages.zh.params.profileMode]
      enabled = true
      title = '雪宁韵'
      subtitle = '“去码头整点薯条”'
      imageUrl = 'images/avatar.webp'
      imageTitle = '雪宁韵'

  [[languages.zh.menu.main]]
    name = '博客'
    url = 'posts/'
    weight = 1

  [[languages.zh.menu.main]]
    name = '关于'
    url = 'about/'
    weight = 2

  [[languages.zh.menu.main]]
    name = '标签'
    url = 'tags/'
    weight = 3

  [[languages.zh.menu.main]]
    name = '归档'
    url = 'archives/'
    weight = 4

  [[languages.zh.menu.main]]
    name = '搜索'
    url = 'search/'
    weight = 5

[languages.en]
  label = 'English'
  weight = 2
  title = 'zeroicey'

  [languages.en.params]
    author = 'zeroicey'
    description = "zeroicey's personal website"
    keywords = ['blog', 'personal', 'hugo']

    [languages.en.params.profileMode]
      enabled = true
      title = 'zeroicey'
      subtitle = 'Go to the dock to order some french fries.'
      imageUrl = 'images/avatar.webp'
      imageTitle = 'zeroicey'

  [[languages.en.menu.main]]
    name = 'Blog'
    url = 'posts/'
    weight = 1

  [[languages.en.menu.main]]
    name = 'About'
    url = 'about/'
    weight = 2

  [[languages.en.menu.main]]
    name = 'Tags'
    url = 'tags/'
    weight = 3

  [[languages.en.menu.main]]
    name = 'Archive'
    url = 'archives/'
    weight = 4

  [[languages.en.menu.main]]
    name = 'Search'
    url = 'search/'
    weight = 5